# Generated by Django 3.0.2 on 2020-03-14 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_form', '0002_clientdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='first_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_form.Clients'),
        ),
    ]
