# Generated by Django 3.0.2 on 2020-03-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_form', '0004_auto_20200314_0651'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientdetail',
            unique_together={('full_name', 'mobile_phone', 'email')},
        ),
    ]
